#!/usr/bin/env python2
#-*- coding: utf-8 -*-

from re import findall
from subprocess import check_output, CalledProcessError
from sys import exit

ok = True

for path in findall(r' [AM]+ (?P<name>.*\.py)', check_output(['git', 'status', '--porcelain'])):
    try:
        print check_output(['pep8', path])
    except CalledProcessError, e:
        ok = False
        print e.output
    else:
        check_output(['git', 'add', path])

if not ok:
    exit(1)
